version: "3"

services:
  habitus_ldap:
    image: osixia/openldap:1.1.8
    container_name: habitus_ldap
    environment:
      - COMPOSE_HTTP_TIMEOUT=200
      - LDAP_LOG_LEVEL=256
      - LDAP_ORGANISATION=Software Architecture
      - LDAP_DOMAIN=arqsoft.unal.edu.co
      - LDAP_BASE_DN=dc=arqsoft,dc=unal,dc=edu,dc=co
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_CONFIG_PASSWORD=config
      - LDAP_READONLY_USER=false
      - LDAP_BACKEND=hdb
      - LDAP_TLS=true
      - LDAP_TLS_CRT_FILENAME=ldap.crt
      - LDAP_TLS_KEY_FILENAME=ldap.key
      - LDAP_TLS_CA_CRT_FILENAME=ca.crt
      - LDAP_TLS_ENFORCE=false
      - LDAP_TLS_CIPHER_SUITE=SECURE256:-VERS-SSL3.0
      - LDAP_TLS_PROTOCOL_MIN=3.1
      - LDAP_TLS_VERIFY_CLIENT=demand
      - LDAP_REPLICATION=false
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=true
      - LDAP_SSL_HELPER_PREFIX=ldap
    tty: true
    stdin_open: true
    volumes:
      - ./data/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
      - ./data/certs:/container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    networks:
      - my-network

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: ldap_client
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=habitus_ldap
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - "8085:80"
    depends_on:
      - habitus_ldap
    networks:
      - my-network

  nodejs-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: habitus_users_ms
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - mongodb
      - habitus_ldap

  mongodb:
    image: mongo:latest
    container_name: habitus_users_db
    ports:
      - "27017:27017"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
