version: "3"
services:
  nodejs-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: habitus_users_ms
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: habitus_users_db
    ports:
      - "27017:27017"
    networks:
      - my-network

networks:
  my-network:
